gateways:
  istio-egressgateway:
    autoscaleEnabled: true
    env: {}
    name: istio-egressgateway
    secretVolumes:
      - mountPath: /etc/istio/egressgateway-certs
        name: egressgateway-certs
        secretName: istio-egressgateway-certs
      - mountPath: /etc/istio/egressgateway-ca-certs
        name: egressgateway-ca-certs
        secretName: istio-egressgateway-ca-certs
    type: ClusterIP
  istio-ingressgateway:
    autoscaleEnabled: true
    env: {}
    name: ${ingressgateway-name}
    secretVolumes:
      - mountPath: /etc/istio/ingressgateway-certs
        name: ingressgateway-certs
        secretName: istio-ingressgateway-certs
      - mountPath: /etc/istio/ingressgateway-ca-certs
        name: ingressgateway-ca-certs
        secretName: istio-ingressgateway-ca-certs
    type: LoadBalancer

meshConfig:
  defaultConfig:
    proxyMetadata:
      ISTIO_META_ENABLE_HBONE: "true"
