global:
  hub: gcr.io/istio-testing
  tag: 0.0.0-ambient.191fe680b52c1754ee72a06b3e0d3f9d116f2e82

  configValidation: true
  defaultNodeSelector: {}
  defaultPodDisruptionBudget:
    enabled: true
  defaultResources:
    requests:
      cpu: 10m
  imagePullPolicy: ""
  imagePullSecrets: []
  istioNamespace: istio-system
  istiod:
    enableAnalysis: false
  jwtPolicy: third-party-jwt
  logAsJson: false
  logging:
    level: default:info
  meshNetworks: {}
  mountMtlsCerts: false
  multiCluster:
    clusterName: ""
    enabled: false
  network: ""
  omitSidecarInjectorConfigMap: false
  oneNamespace: false
  operatorManageWebhooks: false
  pilotCertProvider: istiod
  priorityClassName: ""
  proxy:
    autoInject: enabled
    clusterDomain: cluster.local
    componentLogLevel: misc:error
    enableCoreDump: false
    excludeIPRanges: ""
    excludeInboundPorts: ""
    excludeOutboundPorts: ""
    image: proxyv2
    includeIPRanges: "*"
    logLevel: warning
    privileged: false
    readinessFailureThreshold: 30
    readinessInitialDelaySeconds: 1
    readinessPeriodSeconds: 2
    resources:
      limits:
        cpu: 2000m
        memory: 1024Mi
      requests:
        cpu: 100m
        memory: 128Mi
    statusPort: 15020
    tracer: zipkin
  proxy_init:
    image: proxyv2
    resources:
      limits:
        cpu: 2000m
        memory: 1024Mi
      requests:
        cpu: 10m
        memory: 10Mi
  sds:
    token:
      aud: istio-ca
  sts:
    servicePort: 0
  tracer:
    datadog: {}
    lightstep: {}
    stackdriver: {}
    zipkin: {}
  useMCP: false
