version: "3"

vars:
  CLUSTER_NAME: istio-cilium

tasks:
  cluster:create:
    cmds:
      - |
        kind create cluster --config - <<EOF
        kind: Cluster
        apiVersion: kind.x-k8s.io/v1alpha4
        name: {{ .CLUSTER_NAME }}
        networking:
          disableDefaultCNI: true
          kubeProxyMode: none
        nodes:
        - role: control-plane
        - role: worker
          labels:
            ingress-ready: true
          extraPortMappings:
          - containerPort: 80
            hostPort: 80
            listenAddress: 127.0.0.1
            protocol: TCP
          - containerPort: 443
            hostPort: 443
            listenAddress: 127.0.0.1
            protocol: TCP
        - role: worker
        - role: worker
        EOF

  infra:deploy:
    cmds:
      - terraform apply -var k8s-svc-host={{ .CLUSTER_NAME }}-control-plane

  cluster:delete:
    cmds:
      - kind delete cluster -n {{.CLUSTER_NAME}}
