version: "3"

tasks:
  terratest:
    dir: ./tests
    cmds:
      - go test -v

  apply:
    cmds:
      - terraform apply --auto-approve

  destroy:
    cmds:
      - terraform destroy --auto-approve
